#! /usr/bin/env bash

set -e
set -o pipefail

lastest_url=https://github.com/vesoft-inc/nebula-gears/releases/latest/download/nebula-gears-installer.sh

echo "Start downloading lastest nebula-gears..."
tmpname=/tmp/nebula-gears-installer-latest.sh
rm -rf
curl -Ls $lastest_url -# -o $tmpname

echo "Start installing lastest nebula-gears..."
bash $tmpname $@
rm -f $tmpname
