#! /usr/bin/env bash

# Copyright (c) 2019 vesoft inc. All rights reserved.
#
# This source code is licensed under Apache 2.0 License,
# attached with Common Clause Condition 1.0, found in the LICENSES directory.

# Usage: build-gcc [--prefix=/opt]

# Always use bash
shell=$(basename $(readlink /proc/$$/exe))
if [ ! x$shell = x"bash" ]
then
    bash $0 $@
    exit $?
fi

this_dir=$(dirname $(readlink -f $0))

[[ $# -ne 0 ]] && version=$(echo "$@" | sed 's;.*--version=(\S*).*;\1;p' -rn)

version_files_dir=$this_dir/../share/nebula-gears

mapfile -t all_versions < <( ls -1 $version_files_dir/gcc-tarball-info-* | \
                                awk -F'/' '{print $NF}' | \
                                awk -F'-' '{print $NF}')

[[ -z $version ]] && {
    echo "Please specify the version you want to build with --version=x.y.z" 1>&2;
    echo "Optional versions are: ${all_versions[@]}" 1>&2;
    exit 1;
}

[[ $version = all ]] && version=(${all_versions[@]})
if [[ ${#version[@]} -eq 1 ]]
then
    mapfile -t version < <(echo $version | tr ',' '\n')
fi


[[ $# -ne 0 ]] && prefix=$(echo "$@" | sed 's;.*--prefix=(\S*).*;\1;p' -rn)
prefix=${prefix:-/opt}

if [[ ${#version[@]} -gt 1 ]]
then
    exit_status=0
    for v in ${version[@]}
    do
        $0 --prefix=$prefix --version=$v
        [[ $? -ne 0 ]] && exit_status=$?
    done
    exit $exit_status
fi

# GCC, binutils and support libraries
version_file=$version_files_dir/gcc-tarball-info-$version
[[ -f $version_file ]] || { echo "No version info file found at '$version_file'" 1>&2; exit 1; }
source $version_file

# Building directories setup
cur_dir=$PWD
root_dir=$PWD/toolset-build
tarballs_dir=$root_dir/downloads
source_dir=$root_dir/source
gcc_object_dir=$root_dir/gcc-build-$gcc_version
bu_object_dir=$root_dir/binutils-build-$bu_version
install_dir=$prefix/vesoft/toolset/gcc/$gcc_version
logfile=$root_dir/gcc-build-$gcc_version.log
triplet=x86_64-vesoft-linux
distro=$(lsb_release -si)
glibc_version=$(ldd --version | head -1 | cut -d ' ' -f4 | cut -d '-' -f1)

# Guess number of building jobs
available_mem_mb=$(( $($this_dir/mem-available)/1024 ))
physical_cores=$($this_dir/physical-cores)
building_jobs_num=0
[[ -n $available_mem_mb ]] && jobs_by_mem=$((available_mem_mb / 1024 / 2))
[[ -n $physical_cores ]] && jobs_by_cpu=$physical_cores
[[ -n $jobs_by_mem ]] && building_jobs_num=$jobs_by_mem
[[ -n $jobs_by_cpu ]] && [[ $jobs_by_cpu -lt $jobs_by_mem ]] && building_jobs_num=$jobs_by_cpu
[[ $building_jobs_num -eq 0 ]] && building_jobs_num=1

# Download source tarballs
function get_checksum {
    md5sum $1 | cut -d ' ' -f 1
}

# args: <download command> <tarball> <url> <checksum>
function fetch_tarball {
    local checksum
    [[ -f $2 ]] && checksum=$(get_checksum $2)
    [[ -n $checksum ]] && [[ $checksum = $4 ]] && return 0
    echo "Downloading $2..."
    if ! bash -c "$1 $3"
    then
        echo "Download $2 Failed"
        exit 1
    fi
}

function fetch_tarballs {
    hash wget &> /dev/null && download_cmd="wget -c --progress=bar:force:noscroll"
    if [[ -z $download_cmd ]]
    then
        echo "'wget' not found for downloading" 1>&2;
        exit 1;
    fi
    set +e
    set +o pipefail
    wget --help | grep -q '\--show-progress' && \
            download_cmd="$download_cmd -q --show-progress"
    set -e
    set -o pipefail

    mkdir -p $tarballs_dir && cd $tarballs_dir

    fetch_tarball "$download_cmd" $gcc_tarball $gcc_url $gcc_checksum
    fetch_tarball "$download_cmd" $gmp_tarball $gmp_url $gmp_checksum
    fetch_tarball "$download_cmd" $mpfr_tarball $mpfr_url $mpfr_checksum
    fetch_tarball "$download_cmd" $mpc_tarball $mpc_url $mpc_checksum
    fetch_tarball "$download_cmd" $bu_tarball $bu_url $bu_checksum

    cd $OLDPWD
}

# Unpack source tarballs
function unpack_tarballs {
    mkdir -p $source_dir
    cd $tarballs_dir

    if [[ ! -d $source_dir/gcc-$gcc_version ]]
    then
        echo "Unpacking $gcc_tarball..."
        tar -xf $gcc_tarball -C $source_dir || exit 1
    fi

    if [[ ! -d $source_dir/gmp-$gmp_version ]]
    then
        echo "Unpacking $gmp_tarball..."
        tar -xf $gmp_tarball -C $source_dir || exit 1
    fi

    if [[ ! -d $source_dir/mpfr-$mpfr_version ]]
    then
        echo "Unpacking $mpfr_tarball..."
        tar -xf $mpfr_tarball -C $source_dir || exit 1
    fi

    if [[ ! -d $source_dir/mpc-$mpc_version ]]
    then
        echo "Unpacking $mpc_tarball..."
        tar -xf $mpc_tarball -C $source_dir || exit 1
    fi

    if [[ ! -d $source_dir/binutils-$bu_version ]]
    then
        echo "Unpacking $bu_tarball..."
        tar -xf $bu_tarball -C $source_dir || exit 1
    fi

    cd $OLDPWD
}

# Necessary dependency setup
function setup_deps {
    cd $source_dir/gcc-$gcc_version
    ln -sf ../gmp-$gmp_version gmp
    ln -sf ../mpfr-$mpfr_version mpfr
    ln -sf ../mpc-$mpc_version mpc

    #[[ ! -e config.guess.orig ]] && cp -vp config.guess config.guess.orig
    #cat > config.guess <<EOF
##! /usr/bin/env bash
#this_dir=\$(dirname \$0)
#\$this_dir/config.guess.orig | sed -r 's/-unknown-|-pc-/-vesoft-/'
#EOF
    #chmod +x config.guess

    cd $OLDPWD

    # Tweak GMP to not build with native code
    cd $source_dir/gmp-$gmp_version
    cp -f configfsf.guess config.guess
    cp -f configfsf.sub config.sub

    cd $OLDPWD
}

function version_cmp {
    mapfile -t left < <( echo $1 | tr . '\n' )
    mapfile -t right < <( echo $2 | tr . '\n')
    local i
    for i in ${!left[@]}
    do
        local lv=${left[$i]}
        local rv=${right[$i]}
        [[ -z $rv ]] && { echo $lv; return; }
        [[ $lv -ne $rv ]] && { echo $((lv - rv)); return; }
    done
    ((i++))
    rv=${right[$i]}
    [[ ${#right[@]} -gt ${#left[@]} ]] && { echo $((0-rv)); return; }
}

# Configure GCC
function configure_gcc {
    mkdir -p $gcc_object_dir
    cd $gcc_object_dir
    local host_gcc_version=$(gcc -dumpfullversion -dumpversion)
    local enable_lto=yes
    if [[ $(version_cmp $host_gcc_version 4.5.0) -lt 0 ]]
    then
        enable_lto=no
    fi
    $source_dir/gcc-$gcc_version/configure      \
        --prefix=$install_dir                   \
        --with-pkgversion="Nebula Graph Build"  \
        --enable-shared                         \
        --enable-threads=posix                  \
        --enable-__cxa_atexit                   \
        --enable-clocale=gnu                    \
        --enable-languages=c,c++                \
        --enable-lto=$enable_lto                \
        --enable-bootstrap                      \
        --disable-nls                           \
        --disable-multilib                      \
        --disable-install-libiberty             \
        --with-system-zlib                      \
        --build=$triplet                        \
        --host=$triplet                         \
        --target=$triplet                       \
        --disable-werror
    [[ $? -ne 0 ]] && { echo "Failed to configure GCC" 1>&2;  exit 1; }
    cd $OLDPWD
}

# Start building GCC
function build_gcc {
    cd $gcc_object_dir
    make -s -j $building_jobs_num bootstrap-lean
    [[ $? -ne 0 ]] && { echo "Failed to build GCC" 1>&2; exit 1; }
    cd $OLDPWD
}

# Install GCC
function install_gcc {
    cd $gcc_object_dir
    make -s -j $building_jobs_num install-strip
    [[ $? -ne 0 ]] && { echo "Failed to install GCC" 1>&2; exit 1; }
    cd $OLDPWD
}

# Clean GCC
function clean_gcc {
    rm -rf $gcc_object_dir
}

# Configure binutils
function configure_binutils {
    mkdir -p $bu_object_dir
    cd $bu_object_dir
    $source_dir/binutils-$bu_version/configure  \
        --prefix=$install_dir                   \
        --with-pkgversion="Nebula Graph Build"  \
        --disable-shared                        \
        --disable-nls                           \
        --enable-gold                           \
        --enable-plugins                        \
        --enable-ld=default                     \
        --with-system-zlib                      \
        --build=$triplet                        \
        --host=$triplet                         \
        --target=$triplet                       \
        --disable-werror
    [[ $? -ne 0 ]] && { echo "Failed to configure binutils" 1>&2; exit 1; }
    cd $OLDPWD
}

# Build binutils
function build_binutils {
    cd $bu_object_dir
    make -s -j $building_jobs_num || { echo "Failed to build binutils" 1>&2; exit 1; }
    cd $OLDPWD
}

# Install binutils
function install_binutils {
    cd $bu_object_dir
    make -s install-strip || { echo "Failed to install binutils" 1>&2; exit 1; }
    cd $OLDPWD
    cd $install_dir
    # Place a copy of assembler and linker to libexec
    cp -vp bin/as libexec/gcc/$triplet/$gcc_version
    cp -vp bin/ld* libexec/gcc/$triplet/$gcc_version
    cd $OLDPWD
}

# Clean binutils
function clean_binutils {
    rm -rf $bu_object_dir
}

# Finalize the building
function finalize {
    # Remove all of the annoying libtool files,
    # so that the installation could be copied around
    find $install_dir -name '*.la' | xargs rm -f
}

# Test usability of GCC
function usability_test {
    CXX=$install_dir/bin/g++ $this_dir/cxx-compiler-usability-test
    [[ $? -eq 0 ]] || exit 1
    cp -p $this_dir/cxx-compiler-usability-test $install_dir
}

# Build a self-extractable package
function make_package {
    exec_file=$root_dir/vesoft-gcc-$gcc_version-$distro-x86_64-glibc-$glibc_version.sh
    echo "Creating self-extractable package $exec_file"
    cat > $exec_file <<EOF
#! /usr/bin/env bash
set -e

[[ \$# -ne 0 ]] && prefix=\$(echo "\$@" | sed 's;.*--prefix=(\S*).*;\1;' -r)
prefix=\${prefix:-/opt}/vesoft/toolset

hash xz &> /dev/null || { echo "xz: Command not found"; exit 1; }

mkdir -p \$prefix
[[ -w \$prefix ]] || { echo "\$prefix: No permission to write"; exit 1; }

archive_offset=\$(awk '/^__start_of_archive__$/{print NR+1; exit 0;}' \$0)
tail -n+\$archive_offset \$0 | tar --numeric-owner -xJf - -C \$prefix

echo "GCC-$gcc_version has been installed to \$prefix/gcc/$gcc_version"
echo "Performing usability tests"
CXX=\$prefix/gcc/$gcc_version/bin/g++ \$prefix/gcc/$gcc_version/cxx-compiler-usability-test
echo "Please run 'source \$prefix/gcc/$gcc_version/enable' to start using."
echo "Please run 'source \$prefix/gcc/$gcc_version/disable' to stop using."

exit 0

__start_of_archive__
EOF
    cd $install_dir/../..
    tar -cJf - gcc/$gcc_version >> $exec_file
    chmod 0755 $exec_file
    cd $OLDPWD
}

start_time=$(date +%s)
set -e
set -o pipefail
trap '[[ $? -ne 0 ]] && echo "Building failed, see '$logfile' for more details." 1>&2' EXIT

mkdir -p $root_dir

fetch_tarballs
{
    unpack_tarballs
    setup_deps
}   |& tee $logfile

exec &> >(sed "s/^/\[GCC-$gcc_version\] /")

echo "Starting build GCC-$gcc_version with $building_jobs_num jobs"

{
    configure_gcc
    build_gcc
    install_gcc
    clean_gcc

    configure_binutils
    build_binutils
    install_binutils
    clean_binutils

    finalize
}   |& tee -a $logfile \
    | grep --line-buffered '^Making\|^Configuring\|^Comparing\|^Comparison\|^Failed to'

usability_test

cat > $install_dir/enable <<EOF
this_path=\$(dirname \$(readlink -f \$BASH_SOURCE))
[[ ":\$PATH:" =~ ":\$this_path/bin:" ]] || export PATH=\$this_path/bin:\$PATH
export OLD_CC=\$CC
export OLD_CXX=\$CXX
export CC=\$this_path/bin/gcc
export CXX=\$this_path/bin/g++
hash -r
echo "Only PATH was setup so as not to pollute your library path"
echo "You could run 'export LD_LIBRARY_PATH=\$this_path/lib64:\\\$LD_LIBRARY_PATH' if needed"
EOF

cat > $install_dir/disable <<EOF
this_path=\$(dirname \$(readlink -f \$BASH_SOURCE))
export PATH=\$(echo \$PATH | sed "s#\$this_path/bin:##")
export CC=\$OLD_CC
export CXX=\$OLD_CXX
[ -z \$CC ] && unset CC
[ -z \$CXX ] && unset CXX
hash -r
EOF

cat > $install_dir/version-info <<EOF
Package         : GCC $gcc_version
Distribution    : $distro $(lsb_release -sr)
glibc           : $glibc_version
Arch            : x86_64
Vendor          : VEsoft Inc.
EOF

make_package
end_time=$(date +%s)

echo "GCC-$gcc_version has been installed to $install_dir"
echo "$((end_time - start_time)) seconds been taken."
echo "Run 'source $install_dir/enable' to start using."
echo "Run 'source $install_dir/disable' to disable it."
