#! /bin/bash

if [[ $# -eq 0 ]]
then
    echo "$0 <core file(s)>"
    exit 1
fi

core_bt=$(dirname $0)/core-bt
core_execname=$(dirname $0)/core-execname

if [[ $# -eq 1 ]]
then
    $core_bt $1
else
    for core in $@
    do
        $core_bt $core
        echo
    done
fi

exit 0
