#! /usr/bin/env bash

if [[ $# -eq 0 ]]
then
    echo "$0 <core file(s)>"
    exit 1
fi

function execname() {
    gdb --quiet -nx -c $1 <<EOF 2>&1 |
set width 0
set height 0
set pagination no
info proc mappings
EOF
    sed -n -e '/^[ ]*0x400000.*/p' | sed -e 's#[^/]*\(/.*\)#\1#'
}

if [[ $# -eq 1 ]]
then
    execname $1
else
    for core in $@
    do
        echo "$core: $(execname $core)"
    done
fi

exit 0
