#! /usr/bin/env bash

# Usage: $0 <exe or dso>

set -e
set -o pipefail

ldd -v $1 | \
        egrep 'GLIBC_[.0-9]+' | \
        sed 's/.*(GLIBC_\(.*\)).*/\1/' | \
        sort -t'.' -ug  -k1,1 -k2,2 -k3,3 | \
        tail -1
