#! /usr/bin/env bash

set -e
set -o pipefail

this_dir=$(dirname $(readlink -f $0))

bin_dir_name=$(basename $this_dir)
[[ $bin_dir_name = bin ]] || exit 1

install_prefix=$(dirname $this_dir)
share_dir=$install_prefix/share/nebula-gears
installed_files_file=$share_dir/installed_files

lastest_url=https://github.com/vesoft-inc/nebula-gears/releases/latest/download/nebula-gears-installer.sh

[[ -w $install_prefix ]] || { echo "$install_prefix: No permission to write"; exit 1; }

echo "Start downloading lastest nebula-gears..."
curl -Ls $lastest_url -# -o /tmp/nebula-gears-installer-latest.sh

echo "Unstalling previous installation..."
nebula-gears-uninstall

echo "Start installing lastest nebula-gears..."
bash /tmp/nebula-gears-installer-latest.sh --prefix=$install_prefix
echo "Current version is $(bash /tmp/nebula-gears-installer-latest.sh --version)"

rm -f /tmp/nebula-gears-installer-latest.sh
