#! /usr/bin/env bash

set -e
set -o pipefail

this_dir=$(dirname $(readlink -f $0))

bin_dir_name=$(basename $this_dir)
[[ $bin_dir_name = bin ]] || exit 1

install_prefix=$(dirname $this_dir)
share_dir=$install_prefix/share/nebula-gears
installed_files_file=$share_dir/installed_files

lastest_url=https://github.com/dutor/nebula-gears/releases/latest/download/nebula-gears-installer.sh

[[ -w $install_prefix ]] || { echo "$install_prefix: No permission to write"; exit 1; }

nebula-gears-uninstall

curl -Ls $lastest_url > /tmp/nebula-gears-latest.sh

bash /tmp/nebula-gears-latest.sh

rm -f /tmp/nebula-gears-latest.sh
