#! /bin/bash

function fail() {
    echo $@
    exit 1
}

function soname() {
    readelf -d $1 | grep SONAME | sed -e 's/.*\[\(.*\)\].*/\1/'
}

function getloc() {
    cat $tempdir/$1.loc
}

function get_needed() {
    readelf -d $1 | grep NEEDED | sed -e 's/.*\[\(.*\)\].*/\1/' | grep -v ld
}

[[ $# != 1 ]] && fail "$0 <path/to/executable>"

exe=$1

[[ -f $exe ]] || fail "$exe: No such file"

tempdir=$(mktemp -d /tmp/nebula-ladd.XXXX 2>/dev/null)

echo $tempdir


[[ -d $tempdir ]] || fail "Failed to create temp directory in /tmp"


whole=$(ldd $exe | grep '=>' | awk '{print $3;}')

[[ $whole == "" ]] && exit 0

for lib in $whole
do
    echo $lib >> $tempdir/$(soname $lib).loc
done


collection=

for lib in $(get_needed $exe)
do
    echo $lib >> $tempdir/$(basename $exe)
    collection="$collection $lib"
done

echo $exe:
for x in $collection
do
    echo -e "\t$x"
done

echo

while [[ "$collection" != "" ]]
do
    next=
    for i in $collection
    do
        if [[ -f $tempdir/$i ]]; then
            continue
        fi
        echo $i:
        touch $tempdir/$i
        for j in $(get_needed $(getloc $i))
        do
            next="$next $j"
            echo $j >> $tempdir/$i
            echo -e "\t$j"
        done
        echo
    done
    collection=$next
done


rm -rf $tempdir

exit 0
