name: build

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  gcc:
    name: gcc
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - centos-7
          - centos-8
          - debian-8
          - debian-9
          - debian-10
        arch:
          - linux/amd64
          - linux/arm64
        version:
          - 7.5.0
          - 8.3.0
          - 9.1.0
          - 9.2.0
          - 9.3.0
          - 10.1.0
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: ./docker/images
          file: ./docker/images/buildx/${{ matrix.os }}.Dockerfile
          platforms: ${{ matrix.arch }}
          tags: vesoft/toolset-build:${{ matrix.os }}
          push: false
          build-args: |
            BUILD_GCC_VERSIONS=${{ matrix.version }}
          secrets: |
            "ossutilconfig=${{ secrets.OSS_UTIL_CONFIG }}"

  llvm:
    name: llvm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - centos-7
          - centos-8
          - debian-8
          - debian-9
          - debian-10
        arch:
          - linux/amd64
          - linux/arm64
        version:
          - 8.0.0
          - 9.0.0
          - 10.0.0
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: ./docker/images
          file: ./docker/images/buildx/${{ matrix.os }}.Dockerfile
          platforms: ${{ matrix.arch }}
          tags: vesoft/toolset-build:${{ matrix.os }}
          push: false
          build-args: |
            BUILD_LLVM_VERSIONS=${{ matrix.version }}
          secrets: |
            "ossutilconfig=${{ secrets.OSS_UTIL_CONFIG }}"
